### ISSUE TITLE
Not decrypting

### ISSUE THREAD

**Issue by ghost** [ash47/HappyWheelsTools#1]
Hello.
I am a volunteer of ''FlashPoint''. We archive SWF files. This script is sadly not working on ''game_e_v1_87_g.swf'' Could you fix this issue?

**Comment by ash47** [comment]
I'll see if I can take a look, hopefully it's just a case of pulling out the new keys -- if they completely changed the crypto then it may be harder, I'll do an update if it's easy enough

**Comment by ghost** [comment]
That's great! Thank you for trying on this again.

**Comment by DarkMoe** [comment]
Sorry, this is DarkMoe from Flashpoint, I already decrypted the swf, but for some reason I cannot get it to load from the pre loader swf.

If you are interested in the decrypted swf to see if it can be loaded now, please come to our discord, it's uploaded there

**Comment by DarkMoe** [comment]
@ash47 can you tell us which version of the game used to work with your decrypt tool ? Thanks !
